CREATE TABLE JUGIYO_BBS (
    SEQ_BBS NUMBER(11) PRIMARY KEY,
    SEQ_STORE NUMBER(11) NOT NULL,
    COMMENT_ID VARCHAR2(100) NOT NULL,
    ID_CATEGORY VARCHAR2(100) NOT NULL,
    COMMENTS VARCHAR2(1000) NOT NULL,
    COMMENTS_GROUP_NO NUMBER(11) NOT NULL,
    COMMENTS_REPLY VARCHAR2(10) NOT NULL,
    IMG_URL VARCHAR2(100),
    CREATE_AT DATE NOT NULL,
    UPDATE_AT DATE NOT NULL,
    STATUS VARCHAR2(100) NOT NULL,
    STORE_RATING NUMBER(10),
    CONSTRAINT FK_SEQ_STORE2 FOREIGN KEY(SEQ_STORE)
    REFERENCES JUGIYO_FOOD_STORE(SEQ_STORE)
);

drop table JUGIYO_BBS

CREATE SEQUENCE SEQ_JUGIYO_BBS START WITH 1 INCREMENT BY 1;

SELECT seq_bbs,seq_store,comment_id,id_category,comments,comments_group_no,comments_reply,img_url,create_at,update_at,status,store_rating FROM JUGIYO_BBS  ORDER BY comments_group_no desc,comments_reply asc 

