CREATE TABLE JUGIYO_CUSTOMER (
    CUSTOMER_ID VARCHAR2(100) PRIMARY KEY,
    USER_NAME VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    PHONE_NUMBER VARCHAR2(100) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(100) NOT NULL
);

select * from JUGIYO_CUSTOMER;

update JUGIYO_CUSTOMER set USER_NAME = '문성환' where CUSTOMER_ID = '123'