CREATE TABLE JUGIYO_FOOD_STORE(
    SEQ_STORE NUMBER(11) PRIMARY KEY,
    BOSS_ID VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(100),
    TITLE VARCHAR2(500),
    CONTENT VARCHAR2(4000),
    address VARCHAR2(4000),
    IMG_URL VARCHAR2(100),
    CONSTRAINT FK_BOSS_ID FOREIGN KEY(BOSS_ID)
    REFERENCES JUGIYO_BOSS(BOSS_ID)
);

SELECT * FROM JUGIYO_FOOD_STORE;

-- 테이블 삭제용
DROP TABLE JUGIYO_FOOD_STORE
CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQ_JUGIYO_FOOD_STORE START WITH 1 INCREMENT BY 1;

--셀렉트 테스트
 SELECT SEQ_STORE, BOSS_ID, CATEGORY, TITLE, CONTENT, address, IMG_URL 
 FROM JUGIYO_FOOD_STORE 	
 WHERE BOSS_ID = '123'

SELECT SEQ_STORE, BOSS_ID, CATEGORY, TITLE, CONTENT, address, IMG_URL, status 
FROM JUGIYO_FOOD_STORE 	
WHERE status!='delete'
 
insert into JUGIYO_FOOD_STORE

select * from EMPLOYEES where first_name != 'Steven'

--칼럼 추가
alter table JUGIYO_FOOD_STORE add(status VARCHAR2(100));

-- 업데이트
update JUGIYO_FOOD_STORE 
set status = 'open'
where SEQ_STORE = 50;
