CREATE TABLE JUGIYO_FOOD (
    SEQ_FOOD NUMBER(11) PRIMARY KEY,
    SEQ_STORE NUMBER(11) NOT NULL, 
    FOOD_CATEGORY VARCHAR2(100),
    FOOD_NAME VARCHAR2(100) NOT NULL,
    FOOD_PRICE NUMBER(11) NOT NULL,
    FOOD_SIZE VARCHAR2(100),
    IMG_URL VARCHAR2(100),
    STATUS VARCHAR2(100),
    CONSTRAINT FK_SEQ_STORE4 FOREIGN KEY(SEQ_STORE)
    REFERENCES JUGIYO_FOOD_STORE(SEQ_STORE)    
)


-- 테이블 삭제용
DROP TABLE JUGIYO_FOOD
CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQ_JUGIYO_FOOD START WITH 1 INCREMENT BY 1;

SELECT * FROM JUGIYO_FOOD;

-- 더미데이터
INSERT INTO JUGIYO_FOOD(
SEQ_FOOD, SEQ_STORE, FOOD_CATEGORY, FOOD_NAME, FOOD_PRICE
)
VALUES(SEQ_JUGIYO_FOOD.NEXTVAL,41,'일반','후라이드 치킨','16000')
INSERT INTO JUGIYO_FOOD(
SEQ_FOOD, SEQ_STORE, FOOD_CATEGORY, FOOD_NAME, FOOD_PRICE, IMG_URL
)
VALUES(SEQ_JUGIYO_FOOD.NEXTVAL,28,'치킨','양념 치킨','17000', '/upload/img/sauceChicken.jpg')

update JUGIYO_FOOD 
set IMG_URL = '/upload/img/sauceChicken.jpg'
where SEQ_FOOD = 7;