-- 테이블 생성
CREATE TABLE Foods (
    seqFood int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    seqStore int(11) UNSIGNED NOT NULL,
    foodCategory VARCHAR(100) NOT NULL,
    foodName VARCHAR(100) NOT NULL,
    imgURL VARCHAR(100),
    status VARCHAR(100) NOT NULL,
	PRIMARY KEY(seqFood),
	FOREIGN KEY(seqStore) REFERENCES Foodstores(seqStore) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- 데이터 삭제용
delete from JUGIYO_FOOD
-- 테이블 삭제용
DROP TABLE JUGIYO_FOODS
CASCADE;

CREATE SEQUENCE SEQ_JUGIYO_FOOD START WITH 1 INCREMENT BY 1;

SELECT * FROM JUGIYO_FOOD;

-- 더미데이터
INSERT INTO JUGIYO_FOOD(
SEQ_FOOD, SEQ_STORE, FOOD_CATEGORY, FOOD_NAME, FOOD_PRICE
)
VALUES(SEQ_JUGIYO_FOOD.NEXTVAL,41,'일반','후라이드 치킨','16000')
INSERT INTO JUGIYO_FOOD(
SEQ_FOOD, SEQ_STORE, FOOD_CATEGORY, FOOD_NAME, FOOD_PRICE, IMG_URL
)
VALUES(SEQ_JUGIYO_FOOD.NEXTVAL,28,'치킨','양념 치킨','17000', '/upload/img/sauceChicken.jpg')

-- 업데이트
update JUGIYO_FOOD 
set IMG_URL = '/upload/img/sauceChicken.jpg'
where SEQ_FOOD = 7;