-- 테이블 생성
CREATE TABLE Orders(
    seqOrder int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    seqFoodDetail int(11) UNSIGNED NOT NULL,
    userId VARCHAR(100) NOT NULL,
	createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status VARCHAR(100) NOT NULL,
	PRIMARY KEY(seqOrder, seqFoodDetail),
	FOREIGN KEY(seqFoodDetail) REFERENCES FoodDetails(seqFoodDetail) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(userId) REFERENCES Users(userId) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- 테이블 삭제
DROP TABLE JUGIYO_ORDERs
CASCADE;

CREATE SEQUENCE SEQ_JUGIYO_ORDER START WITH 1 INCREMENT BY 1;

delete from JUGIYO_ORDER

--테이블 조회용
SELECT * FROM JUGIYO_ORDER

-- 테이블 삭제용
DROP TABLE JUGIYO_ORDER
CASCADE CONSTRAINTS;

-- 더미 데이터
INSERT INTO JUGIYO_ORDER(
SEQ_ORDER, SEQ_FOOD, SEQ_STORE, CUSTOMER_ID, CREATE_AT, STATUS, FOOD_NAME, FOOD_PRICE, FOOD_COUNT
)
VALUES(SEQ_JUGIYO_ORDER.NEXTVAL,1,41,'123',SYSDATE,'주문완료','후라이드 치킨','16000', 1)
INSERT INTO JUGIYO_ORDER(
SEQ_ORDER, SEQ_FOOD, SEQ_STORE, CUSTOMER_ID, CREATE_AT, STATUS, FOOD_NAME, FOOD_PRICE, FOOD_COUNT
)
VALUES(1,2,41,'123',SYSDATE,'주문완료','양념 치킨','17000', 1)

