CREATE TABLE JUGIYO_ORDER(
    SEQ_ORDER NUMBER(11) NOT NULL,
    SEQ_FOOD NUMBER(11) NOT NULL,
    CUSTOMER_ID VARCHAR2(100) NOT NULL,
    CREATE_AT DATE NOT NULL,
    STATUS VARCHAR2(100) NOT NULL,
    FOOD_COUNT NUMBER(10) NOT NULL,
    CONSTRAINT PK_JUGIYO_ORDER PRIMARY KEY(SEQ_ORDER,SEQ_FOOD),
    CONSTRAINT FK_SEQ_FOOD FOREIGN KEY(SEQ_FOOD)
    REFERENCES JUGIYO_FOOD(SEQ_FOOD),
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY(CUSTOMER_ID)
    REFERENCES JUGIYO_CUSTOMER(CUSTOMER_ID)    
)

-- 테이블 삭제할때 쓴다
DROP TABLE JUGIYO_ORDER
CASCADE CONSTRAINTS;