CREATE TABLE JUGIYO_ORDER(
    SEQ_ORDER NUMBER(11) NOT NULL,
    SEQ_FOOD NUMBER(11) NOT NULL,
    SEQ_STORE NUMBER(11) NOT NULL,
    CUSTOMER_ID VARCHAR2(100) NOT NULL,
    CREATE_AT DATE NOT NULL,
    STATUS VARCHAR2(100) NOT NULL,
    FOOD_NAME VARCHAR2(100),
    FOOD_PRICE NUMBER(11),
    FOOD_SIZE VARCHAR2(100),
    FOOD_COUNT NUMBER(10) NOT NULL,
    CONSTRAINT PK_JUGIYO_ORDER PRIMARY KEY(SEQ_ORDER,SEQ_FOOD),
    CONSTRAINT FK_SEQ_FOOD FOREIGN KEY(SEQ_FOOD)
    REFERENCES JUGIYO_FOOD(SEQ_FOOD),
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY(CUSTOMER_ID)
    REFERENCES JUGIYO_CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_SEQ_STORE3 FOREIGN KEY(SEQ_STORE)
    REFERENCES JUGIYO_FOOD_STORE(SEQ_STORE)    
)

DROP TABLE JUGIYO_ORDER
CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQ_JUGIYO_ORDER START WITH 1 INCREMENT BY 1;

delete from JUGIYO_ORDER

--테이블 조회용
SELECT * FROM JUGIYO_ORDER

-- 테이블 삭제용
DROP TABLE JUGIYO_ORDER
CASCADE CONSTRAINTS;

-- 더미 데이터
INSERT INTO JUGIYO_ORDER(
SEQ_ORDER, SEQ_FOOD, SEQ_STORE, CUSTOMER_ID, CREATE_AT, STATUS, FOOD_NAME, FOOD_PRICE, FOOD_COUNT
)
VALUES(SEQ_JUGIYO_ORDER.NEXTVAL,1,41,'123',SYSDATE,'주문완료','후라이드 치킨','16000', 1)
INSERT INTO JUGIYO_ORDER(
SEQ_ORDER, SEQ_FOOD, SEQ_STORE, CUSTOMER_ID, CREATE_AT, STATUS, FOOD_NAME, FOOD_PRICE, FOOD_COUNT
)
VALUES(1,2,41,'123',SYSDATE,'주문완료','양념 치킨','17000', 1)

